# 0: 未设置
# 1: 方糖气球 https://sct.ftqq.com/
# 2: 推送加 https://pushplus.hxtrip.com/
send_api: 0
send_key: ""
# 抢排名模式
grab_mode: True

users:
  "id_card_num_here1":
    - "password_here"
  "id_card_num_here2":
    - "password_here"
