# 前往 http://sc.ftqq.com/3.version 获取sckey
sckey: ""

users:
  "id_card_num_here1":
    - "password_here"
    # 校区设置（宝山1/嘉定2/延长3/不在校0）
    # 目前只用每日一报，设置为0即可，但不能为空
    - 0
  "id_card_num_here2":
    - "password_here"
    - 3
