name: Self Report

on:
  schedule:
    - cron: "30 22,4 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Configure OpenVPN
        env:
          users: ${{ secrets.USERS }}
        run: |
          sudo apt update
          sudo apt-get --assume-yes --no-install-recommends install openvpn
          echo "::add-mask::$(python main.py gh-vu)"
          echo "::add-mask::$(python main.py gh-vp)"
          echo "$(python3 main.py gh-vup)" > secret.txt
      - name: Connect to VPN
        run: |
          touch vpn.log
          sudo openvpn --config ".github/vpn/config.ovpn" --log "vpn.log" --daemon
      - name: Test a VPN connection
        timeout-minutes: 1
        run: until ping -c1 xk.autoisp.shu.edu.cn; do sleep 2; done
      - name: Curl IP Getter
        if: always()
        timeout-minutes: 1
        run: curl ipba.cc
      - name: Report Start
        if: always()
        env:
          users: ${{ secrets.USERS }}
          send: ${{ secrets.SEND }}
        run: "python main.py gh-test"
      - name: Kill VPN connection
        if: always()
        run: |
          sudo chmod 777 vpn.log
          sudo killall openvpn
      - name: Upload VPN logs
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: VPN logs
          path: vpn.log